main: de.sandwichfox.ledcontrol.main.Main
name: LEDController
version: 1.1
author: SandwichFox
api-version: 1.19
description: This Plugin is for Controlling LEDs in Minecraft through the GPIO Ports on an Raspberry Pi
website: https://github.com/SandwichFox/MinecraftLEDControl
commands:
  setcolor:
    description: Set the Color of the LED
    usage: /setcolor <color>
    aliases: [sc]